metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    deploymentconfig: kafka
  template:
    metadata:
      labels:
        deploymentconfig: kafka
    spec:
      containers:
      - name: apache-kafka
        image: nferraro/kafka-zookeeper:1.0
        imagePullPolicy: IfNotPresent
        command:
        - bin/kafka-server-start.sh
        args:
        - config/server.properties
        - --override
        - num.partitions=1
        - --override
        - advertised.host.name=kafka
        - --override
        - zookeeper.connect=zookeeper:2181
        volumeMounts:
        - mountPath: /tmp/kafka-logs
          name: kafka-logs
        ports:
        - containerPort: 9092
          name: kafka-port
      volumes:
      - name: kafka-logs
        emptyDir: {}